name: Publish Windows Bundle

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Setup Env
      run: |
        npm i
        npm i -g nexe
    - name: Build bundle
      run: |
        npm run winbundle
    - name: Upload Bundle File
      uses: actions/upload-artifact@v2
      with:
        name: Bundle
        path: dist\*.zip
    - name: Upload Bundle to Release
      uses: svenstaro/upload-release-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist\*.zip
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true

